spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:doonut-test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

# Swagger springdoc-ui Configuration
springdoc:
  swagger-ui:
    path: api
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match:
    - /**


server:
  port: 8081
